CLIENTS_CREATE = "clients.create"
CLIENTS_UPDATE = "clients.update"
CLIENTS_READ = "clients.read"
CLIENTS_LIST = "clients.list"

CASES_CREATE = "cases.create"
CASES_UPDATE = "cases.update"
CASES_READ = "cases.read"
CASES_LIST = "cases.list"

CASE_PARTIES_CREATE = "case_parties.create"
CASE_PARTIES_UPDATE = "case_parties.update"
CASE_PARTIES_READ = "case_parties.read"
CASE_PARTIES_LIST = "case_parties.list"

DOCUMENTS_CREATE = "documents.create"
DOCUMENTS_UPDATE = "documents.update"
DOCUMENTS_READ = "documents.read"
DOCUMENTS_LIST = "documents.list"
DOCUMENTS_UPLOAD = "documents.upload"
DOCUMENTS_DOWNLOAD_URL = "documents.download_url"
DOCUMENTS_PROCESS_REQUESTED = "documents.process_requested"
DOCUMENTS_PROCESS_STARTED = "documents.process_started"
DOCUMENTS_PROCESS_COMPLETED = "documents.process_completed"
DOCUMENTS_PROCESS_FAILED = "documents.process_failed"
DOCUMENTS_CONVERSION_STARTED = "documents.conversion_started"
DOCUMENTS_CONVERSION_COMPLETED = "documents.conversion_completed"
DOCUMENTS_CONVERSION_FAILED = "documents.conversion_failed"
DOCUMENTS_CONVERSION_REQUIRES_OCR = "documents.conversion_requires_ocr"

DOCUMENT_CHUNKS_READ = "document_chunks.read"

AGENT_EXECUTION_CREATED = "agent_execution.created"
AGENT_EXECUTION_STARTED = "agent_execution.started"
AGENT_EXECUTION_COMPLETED = "agent_execution.completed"
AGENT_EXECUTION_FAILED = "agent_execution.failed"
AGENT_EXECUTION_SKIPPED = "agent_execution.skipped"

AUTH_FORBIDDEN = "auth.forbidden"
AUTH_UNAUTHORIZED = "auth.unauthorized"
RBAC_DENIED = "rbac.denied"

ROLES_PERMISSIONS_SEED = "roles_permissions.seed"
